---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.10.4

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[gesto-sftp::default]
